server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garage_mint?currentSchema=grg_mint
    username: ${DB_USER:postgres}
    password: ${DB_PASS:fth-1998}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create-drop   # DEV i√ßin
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: grg_mint
        jdbc:
          time_zone: UTC
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false       # istersen true yap
    schemas: grg_mint
    default-schema: grg_mint
    baseline-on-migrate: true
    locations: classpath:db/migration

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001
